### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ni-ka** [Aldaviva/floorplan#25]
Looks nice, but I am missing some info on how to setup your app.

I cloned the project, ran npm install, created the database and config.json.

Now when I try to add people via /admin I get some errors in the console:

GET http://floorplan.bluejeansnet.com:8080/taas/now?timezone=Europe/London net::ERR_NAME_NOT_RESOLVED jquery.js:6
failed to fetch current london time: error Map.js:232
 Map.js:233
GET http://people/ net::ERR_NAME_NOT_RESOLVED jquery.js:6x.support.cors.e.crossDomain.send jquery.js:6x.extend.ajax jquery.js:6a.ajax backbone.js:1a.sync backbone.js:1h.extend.sync backbone.js:1h.extend.fetch backbone.js:1(anonymous function) admin.js:38(anonymous function) admin.js:59
GET http://localhost:3000/scripts/lib/jquery-2.0.3.min.map 404 (Not Found) :3000/scripts/lib/jquery-2.0.3.min.map:1
GET http://localhost:3000/scripts/lib/backbone-min.map 404 (Not Found) :3000/scripts/lib/backbone-min.map:1

When I click add person I see "You have unsaved changes..."

**Comment by stekkew** [comment]
Hi,

Any update on how to setup this app?

Thanks

**Comment by nikisby** [comment]
Same here, please provide some instructions!!

**Comment by elJoeyJojo** [comment]
i just want to be able to actually install this, anyone can provide a little more details on setting this up?
so far i installed npm, nodejs, mongodb-server then i run npm install config.json and i do get 1 error about a package npm ERR! not a package /home/floorplan/tmp/npm-24362-FadlwEP9/1488484764451-0.8122245138511062/tmp.tgz

i proceed to run node index.js and i get another error


module.js:340
    throw err;
          ^
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/snipeit/seating-chart/floorplan/lib/server.js:1:78)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Aldaviva** [comment]
Added a bunch of usage instructions to the Readme.

**Comment by Abbas53** [comment]
![cmd](https://user-images.githubusercontent.com/30957413/36595625-ae5293cc-18c4-11e8-9efc-d6697f2405d7.jpg)

Can anyone help me. messed up.

**Comment by Aldaviva** [comment]
Why are you asking me how to set up a PHP framework in a 4-month-old, closed thread about improving documentation for a Node.JS project? How did you even find this thread? Are you a spambot?

You don't even have [Git](https://git-scm.com/download/win) on your path.
