### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by ssjbrady** [Aldaviva/floorplan#35]
Hey i need some help. I was able to clone it install the db service and but run into problems with the config.json file 
When installing from the npm i run into a bunch of errors:
npm ERR! not a package /home/user/floorplan/config.json
npm ERR! addLocal Could not install /home/user/floorplan/config.json

The debug file looks like this:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'package.json' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData package.json
8 silly fetchOtherPackageData package.json
9 silly cache add args [ 'package.json', null ]
10 verbose cache add spec package.json
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'package.json',
11 silly cache add   scope: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'package.json',
11 silly cache add   spec: '/home/user/floorplan/package.json',
11 silly cache add   type: 'local' }
12 silly addLocalTarball shasum (computed) 6844bb9c3c02dd21de6d2a3cde0c99b21f36c751
13 verbose addTmpTarball /home/user/floorplan/package.json not in flight; adding
14 verbose addTmpTarball validating metadata from /home/user/floorplan/package.json
15 verbose tar unpack /home/user
/floorplan/package.json
16 verbose tar unpacking to /tmp/npm-11586-fde7ba94/unpack-51a0e890
17 silly gentlyRm /tmp/npm-11586-fde7ba94/unpack-51a0e890 is being purged
18 verbose gentlyRm don't care about contents; nuking /tmp/npm-11586-fde7ba94/unpack-51a0e890
19 silly gunzTarPerm modes [ '775', '664' ]
20 error not a package /home/bradycarmody/floorplan/package.json
21 error addLocal Could not install /home/bradycarmody/floorplan/package.json
22 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open '/tmp/npm-11586-fde7ba94/unpack-51a0e890/package.json'
22 silly fetchPackageMetaData     at Error (native)
22 silly fetchPackageMetaData  error for package.json { [Error: ENOENT: no such file or directory, open '/tmp/npm-11586-fde7ba94/unpack-51a0e890/package.json']
22 silly fetchPackageMetaData   errno: -2,
22 silly fetchPackageMetaData   code: 'ENOENT',
22 silly fetchPackageMetaData   syscall: 'open',
22 silly fetchPackageMetaData   path: '/tmp/npm-11586-fde7ba94/unpack-51a0e890/package.json' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Starting
26 silly runTopLevelLifecycles Finishing
27 silly install printInstalled
28 verbose stack Error: ENOENT: no such file or directory, open '/tmp/npm-11586-fde7ba94/unpack-51a0e890/package.json'
28 verbose stack     at Error (native)
29 verbose cwd /home/user/floorplan
30 error Linux 4.4.0-62-generic
31 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "package.json"
32 error node v4.2.6
33 error npm  v3.5.2
34 error path /tmp/npm-11586-fde7ba94/unpack-51a0e890/package.json
35 error code ENOENT
36 error errno -2
37 error syscall open
38 error enoent ENOENT: no such file or directory, open '/tmp/npm-11586-fde7ba94/unpack-51a0e890/package.json'
39 error enoent ENOENT: no such file or directory, open '/tmp/npm-11586-fde7ba94/unpack-51a0e890/package.json'
39 error enoent This is most likely not a problem with npm itself
39 error enoent and is related to npm not being able to find a file.

**Comment by Aldaviva** [comment]
Added a bunch of installation instructions to the Readme.
