### ISSUE TITLE
Setting up Floorplan

### ISSUE THREAD

**Issue by elJoeyJojo** [Aldaviva/floorplan#38]
Hello,

I've installed Node, NPM and MongoDB on my Linux Ubuntu 16.04 Server. But when I run $ node index.js I get the following error:

floorplan@floorplan:~/floorplan$ node index.js
Listening on http://*:3000
/home/floorplan/floorplan/node_modules/mongodb/lib/mongodb/connection/server.js:481
        throw err;
        ^

TypeError: callback is not a function
    at Server.Base._callHandler (/home/floorplan/floorplan/node_modules/mongodb/lib/mongodb/connection/base.js:378:7)
    at /home/floorplan/floorplan/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at exports.MongoReply.MongoReply.parseBody (/home/floorplan/floorplan/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:137:5)
    at exports.ConnectionPool.<anonymous> (/home/floorplan/floorplan/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
    at emitOne (events.js:115:13)
    at exports.ConnectionPool.emit (events.js:210:7)
    at exports.Connection.<anonymous> (/home/floorplan/floorplan/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
    at emitTwo (events.js:125:13)
    at exports.Connection.emit (events.js:213:7)
    at Socket.<anonymous> (/home/floorplan/floorplan/node_modules/mongodb/lib/mongodb/connection/connection.js:384:22)

Dumb question but Step 5: mentions the dbName of floorplan, is that assumed that the database was created prior to running $ node index.js ?

Thanks and sorry about the trouble.

**Comment by Aldaviva** [comment]
Hmm that's weird. I haven't seen that error before.

The default database name is `floorplan`, but you don't need to manually create it before running the server. Mongo will automatically create the database when you save your first Person document.

**Comment by Aldaviva** [comment]
For reference, here are the software versions I'm using.
- Node 0.10.29
- MongoDB 2.4.14

They're old, I know.

---
Are you using a single MongoDB instance, or a replicaset cluster?

---
You could try changing to a [different version](https://github.com/mongodb/node-mongodb-native/releases) of `mongodb` in `package.json`, running `npm install`, and seeing if that fixes the error for you.

**Comment by elJoeyJojo** [comment]
So you have to use those versions? I'm using this:

floorplan@floorplan:/etc$ mongod --version
db version v3.6.0-rc0
git version: 96dfbfbb8cfc35640034b189ba58fef43751319e
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64

**Comment by menvol3** [comment]
elJoeyJojo, did you resolve the problem ?

**Comment by menvol3** [comment]
After few days trying to install it, i must say it is impossible

**Comment by elJoeyJojo** [comment]
I never used this thing, it's a piece of junk with very to no information and I just wasted my time. They should really delete this repository or make it private. Even if you do get it to work it looks like you're better off writing the whole thing yourself because it's very poorly designed.

**Comment by Aldaviva** [comment]
Too bad for you, @elJoeyJojo. It's very lightweight and simple to install Node, Mongo, and clone this repo. I have it running fine on multiple machines. This project is not a piece of junk, it works quite well and has been for years. I'm certainly not deleting this repository or making it private, as it is very helpful to the people in my company who use it every day, and to all the people who have starred and forked this repo. You probably just think this is poorly designed because you don't understand it, but this project is actually quite elegant, with an optimal balance of functionality without being too complicated. Any problems you have with it are problems with you, not my code. Go take a hike instead of trying to tear down the good work other people have done.
